// Fixed UI copy and message templates. API content and domain identifiers stay separate.
export const strings = {
  common: {
    discoverEvents: 'Discover events',
    tryAgain: 'Try again',
    loading: 'Loading',
    retry: 'Retry',
    retrying: 'Retrying',
    retryingLabel: 'Retrying…',
    goBack: 'Go back',
    you: 'You',
  },
  navigation: {
    discover: 'Discover',
    myEvents: 'My Events',
    community: 'Community events',
    details: 'Event details',
    host: 'Host profile',
    notFound: 'Page not found',
  },
  discover: {
    title: 'Find your people.',
    subtitle: 'Small moments. New connections. Something for everyone.',
    loading: 'Finding your next gathering…',
    empty: 'No events available',
    error: 'Could not load events',
    order: 'Upcoming gatherings first · past events follow',
    all: 'All',
    emptyCategory: (category: string) => `No ${category.toLowerCase()} events`,
  },
  event: {
    loading: 'Loading event…',
    unavailable: 'Event unavailable',
    savedDetails: 'Saved RSVP. Full details are unavailable right now.',
    notFound: 'Event not found',
    notFoundMessage:
      'This event does not exist. Explore other gatherings instead.',
    saved: 'Showing saved event',
    about: 'About this gathering',
    meetHost: 'Meet your host',
    firstAttendee: 'Be the first to join.',
    hostedBy: (name: string) => `Hosted by ${name}`,
    attending: (count: number) => `${count} attending`,
    view: (title: string) => `View ${title}`,
    attendeePreview: (remaining: number) =>
      `Attendee preview${remaining > 0 ? ` · and ${remaining} others` : ''}`,
  },
  host: {
    loading: 'Loading host…',
    unavailable: 'Host unavailable',
    notFound: 'Host not found',
    notFoundMessage: 'This profile is unavailable.',
    events: 'Hosted gatherings',
    empty: 'No hosted events',
  },
  myEvents: {
    title: 'Your next good memory.',
    subtitle: 'All the gatherings you’ve joined, in one place.',
    upcoming: 'Upcoming',
    past: 'Past',
    saving: 'Saving your RSVP changes…',
    refresh: 'Refresh saved events',
    refreshing: 'Refreshing saved events…',
    refreshFailed:
      'Could not refresh events. Your saved RSVPs are still available. Try refreshing again.',
    empty: (tab: string) => `No ${tab.toLowerCase()} RSVPs`,
  },
  rsvp: {
    savingJoined: '✓ Going · Saving…',
    savingJoin: '+ RSVP · Saving…',
    cancel: '✓ Going · Cancel RSVP',
    join: '+ RSVP',
    retry: 'Retry RSVP',
  },
  branding: {
    name: 'GATHER',
    coverTitle: 'Together is better.',
    coverSubtitle: 'COMMUNITY EVENTS',
  },
  grid: {
    empty: 'No events yet',
    emptyMessage: 'Try another category or discover something new to join.',
  },
  errors: {
    demoNotice: 'Showing demo data. Live data unavailable.',
    unexpected: 'Something went wrong',
    reopen: 'Please try opening this screen again.',
    preparing: 'Getting things ready…',
    savedUnavailable: 'Saved events unavailable',
    pageNotFound: 'This page wandered off.',
    pageNotFoundMessage: 'There are still plenty of people to meet.',
    invalidLink: 'Invalid link',
    invalidLinkMessage: 'This link has an invalid identifier.',
    load: 'Unable to load this content. Please try again.',
    fallback: 'Unable to load current data. Showing bundled demo data.',
    restore:
      'Could not restore saved events. Your data has been preserved. Check available storage and try again.',
    save: 'Your RSVP could not be saved. Please try again.',
    syncSaved:
      'Updated event details could not be saved. Your RSVPs are unchanged. Try refreshing again.',
    reset: 'Reset saved RSVPs',
    resetWarning:
      'This will remove all RSVPs saved on this device. You can join events again afterward. Continue?',
    resetConfirm: 'Remove saved RSVPs and continue',
    resetCancel: 'Keep saved RSVPs',
    resetFailed:
      'Could not reset saved RSVPs. Check available storage and try again.',
  },
  categories: {
    Music: 'Music',
    Sports: 'Sports',
    Tech: 'Tech',
    Food: 'Food',
    Other: 'Other',
  },
};
